# Generated by Django 5.2.3 on 2025-07-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
            preserve_default=False,
        ),
    ]
