# Generated by Django 5.2.3 on 2025-07-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cat',
            new_name='product',
        ),
    ]
