# Generated by Django 5.2.4 on 2025-07-19 21:08

from django.db import migrations, models

def copy_addresses_to_fk(apps, schema_editor):
    Supplier = apps.get_model('main_app', 'Supplier')
    Address = apps.get_model('main_app', 'Address')

    for supplier in Supplier.objects.all():
        if not supplier.address:
            continue

        # Naive parser: assumes comma-separated format
        parts = [part.strip() for part in supplier.address.split(',')]

        street = parts[0] if len(parts) > 0 else ''
        city = parts[1] if len(parts) > 1 else ''
        state = parts[2] if len(parts) > 2 else ''
        postal = parts[3] if len(parts) > 3 else ''

        addr = Address.objects.create(
            street_address=street,
            city=city,
            state=state,
            postal_code=postal
        )
        supplier.address_fk = addr
        supplier.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_address_supplier_address_fk'),
    ]

    operations = [
        migrations.RunPython(copy_addresses_to_fk),
    ]
