# Generated by Django 5.2.4 on 2025-07-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_populate_address_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
