# Generated by Django 5.2.4 on 2025-07-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='address_fk',
            new_name='company_address',
        ),
    ]
