# Generated by Django 5.2.4 on 2025-07-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['quantity']},
        ),
    ]
